version: "2"
exclude_patterns:
- "public"
- "database"
- "routes"
- "app/Console"
- "app/Http/Controllers/V1/DashboardController.php"
- "app/Http/Controllers/V1/ValidasiController.php"
- "app/Http/Controllers/V1/VerifikasiController.php"
- "app/Http/Controllers/V1/RegistrasiMandiriController.php"
- "app/Http/Controllers/V1/PCRController.php"
- "app/Http/Controllers/V1/EkstraksiController.php"
- "app/Http/Controllers/V1/SampleController.php"
- "app/Http/Controllers/RegistrasiMandiri.php"
